"""
/***************************************************************************
 TMMTPluginDialog
                                 A QGIS plugin
 This is the management tool for every TEKSI Module installation and upgrade
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-08-28
        git sha              : $Format:%H$
        copyright            : (C) 2024 by TEKSI
        email                : info@teksi.ch
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.PyQt.QtWidgets import QDialog
from teksi_module_management_tool.utils.plugin_utils import PluginUtils

TMMT_UI = PluginUtils.get_ui_class("main_dialog.ui")


class MainDialog(QDialog, TMMT_UI):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)
