# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TMMTPluginDialog
                                 A QGIS plugin
 This is the management tool for every TEKSI Module installation and upgrade
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-08-28
        git sha              : $Format:%H$
        copyright            : (C) 2024 by TEKSI
        email                : info@teksi.ch
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt.QtCore import QSettings
from qgis.PyQt.QtGui import QPixmap
from qgis.PyQt.QtWidgets import QDialog

from ..utils import get_ui_class
from ..utils.plugin_utils import plugin_root_path

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
TMMT_UI = get_ui_class("about_dialog.ui")

class TMMTPluginDialog(QDialog, TMMT_UI):
    def __init__(self, parent=None):
        """Constructor."""
        super(TMMTPluginDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
