"""
/***************************************************************************
 TMMTPlugin
                                 A QGIS plugin
 This is the management tool for every TEKSI Module installation and upgrade
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-08-28
        git sha              : $Format:%H$
        copyright            : (C) 2024 by TEKSI
        email                : info@teksi.ch
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from pathlib import Path

from qgis.PyQt.QtWidgets import QApplication

from .gui.about_dialog import AboutDialog
from .libs.oqtopus.oqtopus_plugin import OqtopusPlugin
from .utils.tmmt_plugin_utils import TMMTPluginUtils


class TMMTPlugin(OqtopusPlugin):
    """
    TEKSI Module Management Tool plugin
    https://github.com/teksi/TMMT
    """

    def __init__(self, iface):
        config = Path(__file__).parent / "default_config.yaml"
        super().__init__(iface, modules_config_path=config, about_dialog_cls=AboutDialog)

        self.__version__ = TMMTPluginUtils.get_plugin_version()
        self.main_menu_name = self.tr(f"&{TMMTPluginUtils.PLUGIN_NAME}")

    # noinspection PyMethodMayBeStatic
    def tr(self, source_text):
        return QApplication.translate("TMMTPlugin", source_text)

    def initGui(self):
        super().initGui()

        self._get_main_menu_action().setIcon(
            TMMTPluginUtils.get_plugin_icon("tmmt-logo.png"),
        )
